# Generated by Django 4.2.3 on 2023-10-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followers", models.IntegerField(default=0)),
                ("following", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="posts_count",
            field=models.IntegerField(default=0),
        ),
    ]
